[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'sudo.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo =  'itchyny/calendar.vim'

[[plugins]]
repo = 'https://github.com/kmnk/vim-unite-giti.git'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'clausreinke/typescript-tools.vim'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'kana/vim-filetype-haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
