[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
  let g:neosnippet#snippets_directory='~/snippets/'
'''
on_i  = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = ['neosnippet']

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'sudo.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
nnoremap <Leader>qa :QuickRun -args
let g:quickrun_config = {
      \  'python':{'command': 'python3'}
      \}
'''

[[plugins]]
repo =  'itchyny/calendar.vim'

[[plugins]]
repo = 'https://github.com/kmnk/vim-unite-giti.git'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
vmap <Enter> <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'clausreinke/typescript-tools.vim'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'kana/vim-filetype-haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = '''
  let g:ref_phpmanual_path = $HOME . '/.config/nvim/ref/php-chunked-xhtml'
'''

[[plugins]]
repo = 'Shougo/vimshell'
hook_add = '''
  nnoremap <Leader>s :VimShell<CR>
'''

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

#[[plugins]]
#repo = 'Shougo/neoinclude.vim'
#depneds = ['deoplete.vim']

[[plugins]]
repo = 'tsukkee/unite-tag'
#depneds = ['unite.vim', 'neoinclude.vim']
depneds = ['unite.vim']
