[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/denite.nvim'
rev = '2.1'
depends = ['neomru.vim']
on_event = ['BufRead']
hook_add = '''
  nnoremap    [denite]   <Nop>
  nmap    <Leader>d [denite]
  nnoremap <silent> [denite]m :<C-u>Denite<Space>file_mru<CR>
  nnoremap <silent> [denite]f :<C-u>DeniteProjectDir<Space>file/rec<Space>-path=`expand('%:p')`<CR>
  nnoremap <silent> [denite]b :<C-u>Denite<Space>buffer<CR>
  nnoremap <silent> [denite]d :<C-u>DeniteBufferDir<Space>-mode=normal<Space>file<Space>file:new<CR>
  nnoremap <silent> [denite]c :<C-u>Denite<Space>-mode=normal<Space>file<Space>file:new<CR>
  nnoremap <silent> [denite]g :<C-u>DeniteProjectDir<Space>grep:<Space>-buffer-name=search-buffer-denite<Space>-path=`expand('%:p')`<CR>
  nnoremap <silent> [denite]r :<C-u>Denite<Space>-resume<Space>-buffer-name=search-buffer-denite<CR>
  nnoremap <silent> [denite]y :<C-u>Denite<Space>neoyank<CR>
'''
hook_source = '''
  call denite#custom#map('insert', '<Esc>', '<denite:enter_mode:normal>')
  call denite#custom#map('normal', '<Esc>', '<denite:quit>')
  call denite#custom#map('normal', '<C-h>', '<denite:move_up_path>')
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'separator', [])
  call denite#custom#var('grep', 'default_opts', ['--nocolor', '--nogroup'])
  call denite#custom#var('grep', 'pattern_opt', [])
	call denite#custom#var('file/rec', 'command',
	\ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
	call denite#custom#var('directory_rec', 'command',
	\ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim']
on_event = ['BufRead']
hook_add = '''
  " The prefix key.
  nnoremap    [unite]   <Nop>
  nmap    <Leader>f [unite]

  " unite.vim keymap
  let g:unite_enable_start_insert = 0
  nnoremap [unite]u  :<C-u>Unite -no-split<Space>
  nnoremap <silent> [unite]d :<C-u>Unite<Space>file<CR>
  nnoremap <silent> [unite]f :<C-u>Unite<Space>buffer<CR>
  nnoremap <silent> [unite]b :<C-u>Unite<Space>bookmark<CR>
  nnoremap <silent> [unite]m :<C-u>Unite<Space>file_mru<CR>
  nnoremap <silent> [unite]r :<C-u>UniteWithBufferDir file file/new -buffer-name=file<CR>
  nnoremap <silent> ,vr :UniteResume<CR>

  nnoremap <silent> [unite]p :<C-u>Unite<Space>history/yank -default-action=yank<CR>

  " unite-build map
  nnoremap <silent> ,vb :Unite build<CR>
  nnoremap <silent> ,vcb :Unite build:!<CR>
  nnoremap <silent> ,vch :UniteBuildClearHighlight<CR>

  " unite-grep
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts = '--nocolor --nogroup'
  let g:unite_source_grep_recursive_opt = ''
  let g:unite_source_grep_max_candidates = 200
'''

[[plugins]]
repo = 'thinca/vim-scouter'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'

[[plugins]]
repo = 'lvht/phpcd.vim'
build = 'php7 /usr/local/bin/composer install'
on_ft = 'php'
hook_add = '''
let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
let g:deoplete#ignore_sources.php = ['omni']
let g:phpcd_auto_restart = 1
nnoremap <C-\> :<C-u>call phpcd#JumpToDefinition('split')<CR><C-w>T
'''
hook_post_source = '''
let g:phpcd_php_cli_executable = 'php7'
'''

[[plugins]]
repo = 'ternjs/tern_for_vim'
build = 'npm install'
on_ft = 'javascript'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'vue']
hook_add = '''
  let g:closetag_filenames = '*.html,*.vue,*.twig'
'''

# lint
[[plugins]]
repo = 'w0rp/ale'
on_ft = ['php']
hook_add = '''
  let g:ale_lint_on_text_changed = 0
  let g:airline#extensions#ale#enabled = 1
  let g:airline#extensions#ale#error_symbol = 'E:'
  let g:airline#extensions#ale#warning_symbol = 'W:'
'''
